server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch_processing
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false

file:
    input: "classpath:data.csv"